# my config
version: 2.1
orbs:
    node: circleci/node@3.0.0
    docker: circleci/docker@2.4.0

jobs:
    build-and-push:
        environment:
            DOCKER_IMAGE: vohaiphuc/img-vite-pin
            DOCKER_TAG: latest
        executor: docker/docker
        steps:
            - setup_remote_docker
            - checkout
            - docker/check:
                  docker-username: DOCKERHUB_USERNAME
                  docker-password: DOCKERHUB_PW
            - docker/build:
                  image: $DOCKER_IMAGE
                  tag: $DOCKER_TAG
            - docker/push:
                  digest-path: /tmp/digest.txt
                  image: $DOCKER_IMAGE
                  tag: $DOCKER_TAG
            - run:
                  command: |
                      echo "Digest is: $(</tmp/digest.txt)"
    deploy:
        executor: docker/docker
        steps:
            - run:
                  name: Debug SSHKEY
                  command: |
                      echo "SSHKEY value: ${SSHKEY}"
            # Please add $SSH_KEY_FINGERPRINT, $DEPLOYED_USER@ and DEPLOYED_SERVER to project's environment
            - add_ssh_keys:
                  fingerprints:
                      - 0f:f6:a0:17:10:23:1d:b7:80:de:73:c1:e7:64:d7:ce
            - run: ssh -p 2018 root@103.97.124.134 './deploy.sh'

workflows:
    my-pipeline:
        jobs:
            # - node/test
            - build-and-push:
                  #   requires:
                  #       - node/test
                  filters:
                      branches:
                          only:
                              - production
            # uncomment the 3 following lines to enable deploying
            - deploy:
                  requires:
                      - build-and-push
